## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
import numpy as np
df = pd.DataFrame(data, columns = ["name","job","family_size","num_cars"])
print(df[[np.logical_or (df.job == "psychologist" , df.job == "teacher" )] and (df.num_cars > df.family_size)]) #use "and"
print(df[(df.family_size <= 2) & (df.num_cars >= 1)]) #use "&"
print(df.job.unique())

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
data = {"fruit" : fruit, "weights" :weights}
df = pd.DataFrame(data, columns = ["fruit" , "weights"])
apple = df[df.fruit == "apple"]
banana = df[df.fruit == "banana"]
carrot = df[df.fruit == "carrot"]
print("Apple:", np.average(apple.weights))
print("Banana:", np.average(banana.weights))
print("Carrot:", np.average(carrot.weights))

Apple: 5.666666666666667
Banana: 5.75
Carrot: 5.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
course_name.sort()
Python_index = np.where(course_name == "Python")   #np.where returns a array 
JS_index = np.where(course_name == "JS")
examples_index = np.where(course_name == "examples")
PHP_index = np.where(course_name == "PHP")
html_index =  np.where(course_name == "html")
print(Python_index[0], JS_index[0], examples_index[0], PHP_index[0], html_index[0])

for i in course_name:
  for j in i.split():
    if j.startswith("P"):
      print("True")
    else:
      print("False")
    



[2] [0] [3] [1] [4]
False
True
True
False
False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [3]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [5]:
# Type your solution here
student_id_reversed = np.flip(student_id)
print("Reversed array:", student_id_reversed)
print("Original array:", student_id)

student_id.sort()
print(student_id[-3:])


Reversed array: [4532 5241 1682 1671 6230 5202 1023]
Original array: [1023 5202 6230 1671 1682 5241 4532]
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [8]:
# Type your solution here

# Hint: you can use arange to start off
s = np.arange(1,100)
print(np.sum(s[np.logical_or(s % 3 == 0, s % 5 == 0)]))

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [13]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# Type your solution here
c0 = arr[:,0]
c3 = arr[:,3]
temp = []
c1 = arr[:,1]
c2 = arr[:,2]
temp = c1
c1 = c2
c2 = temp
swap = np.array([c0,c1,c2,c3]).transpose()
print(swap)

r2 = arr[2,:]
temp2 = []
r0 = arr[0,:]
r1 = arr[1,:]
temp2 = r0
r0 = r1
r1 = temp2
swap2 = np.array([r0,r1,r2])
print(swap2)


[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
